### PR TITLE
chore(generation): keep BUILD file

### PR DESCRIPTION
**Pull request by pregnor**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | -
| License         | Apache 2.0

### What's in this PR?

This workaround saves the plz BUILD configuration file. 

### Why?

The OpenAPI code regeneration deletes all generated files. 

### Additional context

Tried moving it to the .gen/pipeline/go directory in advance or moving away and back before the generation completes, but those approaches did not work.

### Checklist

- ~Implementation tested (with at least one cloud provider)~
- ~Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)~
- ~OpenAPI and Postman files updated (if needed)~
- ~User guide and development docs updated (if needed)~
- ~Related Helm chart(s) updated (if needed)~

### CODE REVIEW

**Comment by orymate** [comment]
shouldn't we add `/tmp` to gitignore?

**Comment by pregnor** [comment]
> shouldn't we add /tmp to gitignore?
`tmp` is left empty after the process so no difference happens as git doesn't care about empty directories, only files, but I can add it to the ignored files list, give me a sec.

**Comment by pregnor** [comment]
The process could even be improved if I were capable of specifying cascadic delete from `tmp/.gen/pipeline/pipeline/BUILD` upwards through empty directories, going to check that idea out.

**Comment by pregnor** [comment]
Significant changes were pushed so I re-requested the reviews as a dismissal of previous approves in order to ensure integrity.

**Comment by sagikazarmark** [comment]
Doesn't matter that much, it's temporary anyway

**Pull request merged**
