### PR TITLE
Fix kubicorn.io url in readme

### PR DESCRIPTION
**Pull request by mhmxs**
@matyix

### CODE REVIEW

**Comment by matyix** [comment]
@mhmxs can you please do another `fake` commit - I can't merge it until CircleCI does not validate the build, etc however building of forks was switched off so we are in the `nowhere` land. Thank for the PR, switched on the fork builds on CircleCI.

**Comment by mhmxs** [comment]
@matyix something still wrong:
```
Error parsing reference: "/pipeline-prod:91" is not a valid repository/tag
Exited with code 1
```

**Comment by matyix** [comment]
Thanks @mhmxs - I suspect these are be [related](https://github.com/banzaicloud/pipeline/issues/45). CircleCI is pushing the images which are not available for those not in the org.

**Comment by matyix** [comment]
@mhmxs this [PR](https://github.com/banzaicloud/pipeline/pull/59) is fixing your issue.

**Comment by matyix** [comment]
@mhmxs it took a bit longer than expected - a simple change traced down an  explored path in the CI process (building PR's from people outside the org), so thanks again it was useful.

**Pull request merged**
